//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackMeUp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackMeUp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackMeUp.
        /// </summary>
        internal static string AppFolder {
            get {
                return ResourceManager.GetString("AppFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets\Icons\BackMeUpLogo.ico.
        /// </summary>
        internal static string AppIcon {
            get {
                return ResourceManager.GetString("AppIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icons/BackMeUpLogo.ico.
        /// </summary>
        internal static string AppTitleBarIcon {
            get {
                return ResourceManager.GetString("AppTitleBarIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups.
        /// </summary>
        internal static string BackupFolder {
            get {
                return ResourceManager.GetString("BackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.linkedin.com/in/herediamarcelo/.
        /// </summary>
        internal static string ContactUrl {
            get {
                return ResourceManager.GetString("ContactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Images/lamp.gif.
        /// </summary>
        internal static string CreateBackupImage {
            get {
                return ResourceManager.GetString("CreateBackupImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Souls II.
        /// </summary>
        internal static string DS2Name {
            get {
                return ResourceManager.GetString("DS2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Souls III.
        /// </summary>
        internal static string DS3Name {
            get {
                return ResourceManager.GetString("DS3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Souls Remastered.
        /// </summary>
        internal static string DSRName {
            get {
                return ResourceManager.GetString("DSRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont Know Yet.
        /// </summary>
        internal static string EldenRingName {
            get {
                return ResourceManager.GetString("EldenRingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalSettings.json.
        /// </summary>
        internal static string LocalSettingsFile {
            get {
                return ResourceManager.GetString("LocalSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekiro.
        /// </summary>
        internal static string SekiroName {
            get {
                return ResourceManager.GetString("SekiroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppBackgroundRequestedTheme.
        /// </summary>
        internal static string ThemeSettingsKey {
            get {
                return ResourceManager.GetString("ThemeSettingsKey", resourceCulture);
            }
        }
    }
}
